In [1]:
import os
import pandas as pd
#from pandas_profiling import ProfileReport
import seaborn as sns
import matplotlib.pyplot as plt


%matplotlib inline

In [2]:
os.chdir("../tratados")
os.getcwd()

'/home/antero/Documentos/TCC/tratados'

In [3]:
df_imdb = pd.read_csv('df_imdb_tratado.csv', sep=',', na_values='\\N', low_memory=False)

In [4]:
df_oscar=pd.read_csv('df_oscar_tratado.csv')

In [5]:
df_rotten = pd.read_csv('df_rotten_tomatoes_tratado.csv',sep=',')

In [6]:
df_imdb_oscar = df_imdb.merge(df_oscar, left_on=['primaryTitle','startYear'], right_on=['film','year_film'], how='outer')

In [7]:
df_imdb_oscar_rotten = df_imdb_oscar.merge(df_rotten, left_on=['primaryTitle','startYear'],right_on=['movie_title','year'], how='outer')

In [8]:
df_imdb_oscar_rotten

,titleType,primaryTitle,originalTitle,isAdult,startYear,genres,averageRating,numVotes,year_film,year_ceremony,...,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count,year
0,short,Carmencita,Carmencita,0.0,1894.0,"Documentary,Short",5.7,1684.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,short,Le clown et ses chiens,Le clown et ses chiens,0.0,1892.0,"Animation,Short",6.0,207.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,short,Pauvre Pierrot,Pauvre Pierrot,0.0,1892.0,"Animation,Comedy,Romance",6.5,1421.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,short,Un bon bock,Un bon bock,0.0,1892.0,"Animation,Short",6.1,121.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,short,Blacksmith Scene,Blacksmith Scene,0.0,1893.0,"Comedy,Short",6.1,2221.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Fresh,73.0,40.0,Upright,88.0,1907.0,14.0,29.0,11.0,1973.0
450230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Fresh,69.0,36.0,Spilled,31.0,3657.0,7.0,25.0,11.0,2015.0
450231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Rotten,42.0,26.0,Upright,69.0,20323.0,1.0,11.0,15.0,1980.0
450232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Rotten,39.0,64.0,Spilled,30.0,7652.0,16.0,25.0,39.0,2008.0
450233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Rotten,4.0,68.0,Spilled,33.0,11369.0,19.0,3.0,65.0,2006.0