In [6]:
import os
os.getcwd()

'/home/antero/Work/notebooks'

In [7]:
import pandas as pd

In [8]:
df_oscar=pd.read_csv("../microdados/the_oscar_award.csv", sep=',')

In [9]:
df_oscar

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...,...,...
10390,2019,2020,92,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True
10391,2019,2020,92,JEAN HERSHOLT HUMANITARIAN AWARD,Geena Davis,NaN,True
10392,2019,2020,92,HONORARY AWARD,David Lynch,NaN,True
10393,2019,2020,92,HONORARY AWARD,Wes Studi,NaN,True
10394,2019,2020,92,HONORARY AWARD,Lina Wertmüller,NaN,True

In [10]:
df_oscar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10395 entries, 0 to 10394
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year_film      10395 non-null  int64
 1   year_ceremony  10395 non-null  int64
 2   ceremony       10395 non-null  int64
 3   category       10395 non-null  object
 4   name           10395 non-null  object
 5   film           10091 non-null  object
 6   winner         10395 non-null  bool
dtypes: bool(1), int64(3), object(3)
memory usage: 497.5+ KB

In [11]:
cols_imdb = ['tconst','titleType','primaryTitle','originalTitle', 'genres','startYear']

In [12]:
df_imdb_basics = pd.read_csv('../microdados/title.basics.tsv', sep='\t', usecols=cols_imdb, na_values='\\N')

In [15]:
df_imdb_basics

,tconst,titleType,primaryTitle,originalTitle,startYear,genres
0,tt0000001,short,Carmencita,Carmencita,1894.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,1892.0,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,1892.0,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,1892.0,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,1893.0,"Comedy,Short"
...,...,...,...,...,...,...
7135028,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,2010.0,"Action,Drama,Family"
7135029,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,2010.0,"Action,Drama,Family"
7135030,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,2010.0,"Action,Drama,Family"
7135031,tt9916856,short,The Wind,The Wind,2015.0,Short
7135032,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,2014.0,"Animation,Comedy,Family"

In [13]:
df_imdb_ratings = pd.read_csv('../microdados/title.ratings.tsv', sep='\t', na_values='\\N')

In [25]:
df_imdb = df_imdb_basics.merge(df_imdb_ratings,left_on='tconst',right_on='tconst')

In [26]:
df_imdb

,tconst,titleType,primaryTitle,originalTitle,startYear,genres,averageRating,numVotes
0,tt0000001,short,Carmencita,Carmencita,1894.0,"Documentary,Short",5.6,1646
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,1892.0,"Animation,Short",6.1,198
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,1892.0,"Animation,Comedy,Romance",6.5,1345
3,tt0000004,short,Un bon bock,Un bon bock,1892.0,"Animation,Short",6.2,120
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,1893.0,"Comedy,Short",6.1,2131
...,...,...,...,...,...,...,...,...
1071692,tt9916580,tvEpisode,Horrid Henry Horrid Boy?,Horrid Henry Horrid Boy?,2012.0,"Animation,Comedy,Family",7.2,5
1071693,tt9916690,tvEpisode,Horrid Henry Delivers the Milk,Horrid Henry Delivers the Milk,2012.0,"Animation,Comedy,Family",6.6,5
1071694,tt9916720,short,The Nun 2,The Nun 2,2019.0,"Comedy,Horror,Mystery",5.8,60
1071695,tt9916766,tvEpisode,Episode #10.15,Episode #10.15,2019.0,"Family,Reality-TV",6.9,14
1071696,tt9916778,tvEpisode,Escape,Escape,2019.0,Drama,7.3,24

In [53]:
df_imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7135033 entries, 0 to 7135032
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   tconst         object
 1   titleType      object
 2   primaryTitle   object
 3   originalTitle  object
 4   startYear      float64
 5   genres         object
dtypes: float64(1), object(5)
memory usage: 326.6+ MB

In [54]:
df_imdb.titleType.unique()

array(['short', 'movie', 'tvMovie', 'tvSeries', 'tvEpisode', 'tvShort',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame'], dtype=object)

In [ ]:
df_IMDB_OSCAR = df_oscar.merge(df_imdb_filtered, left_on=['film','year_film'], right_on=['primaryTitle','startYear'])

In [55]:
type_movie=['movie']

In [56]:
df_imdb_filtered =df_imdb[df_imdb.titleType.isin(type_movie)]

In [57]:
df_IMDB_OSCAR = df_oscar.merge(df_imdb_filtered, left_on=['film','year_film'], right_on=['primaryTitle','startYear'])

In [58]:
df_IMDB_OSCAR

,year_film,year_ceremony,ceremony,category,name,film,winner,tconst,titleType,primaryTitle,originalTitle,startYear,genres
0,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True,tt0018379,movie,7th Heaven,7th Heaven,1927.0,"Drama,Romance"
1,1927,1928,1,ART DIRECTION,Harry Oliver,7th Heaven,False,tt0018379,movie,7th Heaven,7th Heaven,1927.0,"Drama,Romance"
2,1927,1928,1,DIRECTING (Dramatic Picture),Frank Borzage,7th Heaven,True,tt0018379,movie,7th Heaven,7th Heaven,1927.0,"Drama,Romance"
3,1927,1928,1,OUTSTANDING PICTURE,Fox,7th Heaven,False,tt0018379,movie,7th Heaven,7th Heaven,1927.0,"Drama,Romance"
4,1927,1928,1,WRITING (Adaptation),Benjamin Glazer,7th Heaven,True,tt0018379,movie,7th Heaven,7th Heaven,1927.0,"Drama,Romance"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7798,2019,2020,92,SHORT FILM (Live Action),Meryam Joobeur and Maria Gracia Turgeon,Brotherhood,False,tt7220118,movie,Brotherhood,Brotherhood,2019.0,Drama
7799,2019,2020,92,SOUND MIXING,"Gary Rydstrom, Tom Johnson and Mark Ulano",Ad Astra,False,tt2935510,movie,Ad Astra,Ad Astra,2019.0,"Adventure,Drama,Mystery"
7800,2019,2020,92,VISUAL EFFECTS,"Dan DeLeeuw, Russell Earl, Matt Aitken and Dan...",Avengers: Endgame,False,tt4154796,movie,Avengers: Endgame,Avengers: Endgame,2019.0,"Action,Adventure,Drama"
7801,2019,2020,92,VISUAL EFFECTS,"Robert Legato, Adam Valdez, Andrew R. Jones an...",The Lion King,False,tt6105098,movie,The Lion King,The Lion King,2019.0,"Adventure,Animation,Drama"
7802,2019,2020,92,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False,tt8946378,movie,Knives Out,Knives Out,2019.0,"Comedy,Crime,Drama"

In [51]:
df_IMDB_OSCAR.to_csv('df_imdb_oscar.csv')